### ISSUE TITLE
[Crash Report] "List is empty" after multi selection

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#254]
### Crash log

```
Crash Report:

App version:     1.8.5.1 (1085)
Git Commit Hash: d37a3b69c8c70fcc49693df53d9bd02dd33f775a
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 14 (API 34)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             SM6375/unknown (by QTI)
Device brand:    unknown (by unknown)
Device model:    unknown/unknown (code unknown)
Build version:   unknown
                 (T.R4T2.150e109-1-3)
Language:        de
Memory:          2604/7397
Screen:          2161x1080 (dpi 480)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.util.NoSuchElementException: List is empty.
        at i9.m.v0(SourceFile:22)
        at af.r1.invokeSuspend(SourceFile:98)
        at o9.a.resumeWith(SourceFile:9)
        at ma.a.j(SourceFile:124)
        at ha.a.j0(SourceFile:99)
        at ha.z.s(SourceFile:36)
        at af.h1.d(SourceFile:169)
        at af.k.onMenuItemClick(SourceFile:112)
        at n.l.q(SourceFile:19)
        at n.t.onItemClick(SourceFile:39)
        at android.widget.AdapterView.performItemClick(AdapterView.java:352)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1277)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3294)
        at android.os.Handler.handleCallback(Handler.java:958)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:257)
        at android.os.Looper.loop(Looper.java:368)
        at android.app.ActivityThread.main(ActivityThread.java:8821)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        Suppressed: ma.e: [n1{Cancelling}@727f00f, Dispatchers.Main.immediate]
```

### Version

1.8.5.1 (1085)

### Steps to reproduce the bug

1. Select "Song" tab
2. Start multi selection
3. Select at least two list items
4. Select "Tags ändern" from context menu
5. Crash

### Environment

LOS 21

**Comment by chr56** [comment]
Confirmed, this only happened when selection has no songs (like selecting empty playlists).

Fixed in ca0fadd4.

**Comment by eku** [comment]
> this only happened when selection has no songs

How can this happen? I selected two songs, so the list should have not been empty.

**Comment by chr56** [comment]
> How can this happen? 

I don't know. 

That is what the retraced stacktrace tells me. And I reproduced it by this way (not yours), and fixed it for this way.

Test yourself [here](https://github.com/user-attachments/files/18124116/EmptySelectionFix.zip).

**Comment by chr56** [comment]
[v1.9.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.9.0) has been released finally! 

Close!

**Comment by eku** [comment]
Hi @chr56 

The app does no longer crash. However you still can't multi-edit tags. It now does nothing rather then crashing.

Something strange is broken. Interestingly, only on one of my two Android 14 phones, the one that showed the crash.
